### ISSUE TITLE
Add option to have custom separator between styles, markup and scripts 

### ISSUE THREAD

**Issue by MananTank** [sveltejs/prettier-plugin-svelte#111]
**Why Add this ?**
sometimes it becomes very hard to separate sections when the component is complicated.
I usually prefer 2-3 newlines between each section, so that  I can easily differentiate sections.

**Example 1:** : Put 2 new lines between sections
```json
{
 "svelteSectionSeperator": "\n\n" 
}
```

```html
<script> ..... </script>


<abc> ....</abc>
<xyz> ....</xyz>


<style> ..... </style>
```

**Example 2:** :

```json
{
 "svelteSectionSeperator": "\n <!------------- > \n" 
}
```

```html
<script> ..... </script>

<!------------- >

<abc> ....</abc>
<xyz> ....</xyz>

<!------------- >

<style> ..... </style>
```

**Comment by llamerr** [comment]
Looking for same feature but to separate redux actions/types/other stuff to make it readable. Any info on this exists?

**Comment by dummdidumm** [comment]
With #314 implemented you can chose `svelteSortOrder: none` and put any number of comments between the script/style/html sections to get what you want. I don't think a separate option for this specific use case would be good, we need to keep the number of options lean - therefore closing this.
