### ISSUE TITLE
Invalid typescript syntax destroys file content

### ISSUE THREAD

**Issue by vsviridov** [sveltejs/prettier-plugin-svelte#115]
I've started using the new TypeScript support, and accidentally wrote following code:

```
<script type="ts">
   let export foo: string = ""
</script>
```

Notice that is said `let export` instead of `export let`.

When reformatted by my formatter - the code was destroyed (replaced with following:
```json
{
      "type": "Script",
      "start": 0,
      "end": 499,
      "context": "default",
      "content": {
          "type": "Program",
          "start": 488,
          "end": 490,
          "loc": {
              "start": {
                  "line": 1,
                  "column": 0
              },
              "end": {
                  "line": 1,
                  "column": 490
              }
          },
          "body": [
              {
                  "type": "BlockStatement",
                  "start": 488,
                  "end": 490,
                  "loc": {
                      "start": {
                          "line": 1,
                          "column": 488
                      },
                      "end": {
                          "line": 1,
                          "column": 490
                      }
                  },
                  "body": []
              }
          ],
          "sourceType": "module"
      },
      "attributes": [
          {
              "type": "Attribute",
              "name": "lang",
              "value": [
                  {
                      "type": "Text",
                      "data": "ts",
                      "start": 6,
                      "end": 8
                  }
              ],
              "start": 0,
              "end": 9
          }
      ]
  }
```

Which is pretty annoying... If I run the prettier instance manually I do get the error, but I also get the stdout output with that JSON AST representation, because there's a `console.log(JSON.stringify(node, null, 4))` in the plugin.js:457, which is interpreted by the formatter as the new file contents. At least redirect that output to `stderr` so it doesn't confuse the tooling.

**Comment by toerndev** [comment]
Was going to report the same problem. I'm guessing that vscode treats stdout differently since more people aren't reporting this? I use the vim plugin `w0rp/ale` to call prettier via eslint-plugin-prettier. Removing the `console.log` in `node_modules` fixes the problem temporarily.

I hope no editors are relying on this output so it can be a quick fix. Would create a PR but it's just one line and I don't yet understand why the author put it there, so...
