### ISSUE TITLE
VSCode auto formatter compresses each loop to single line

### ISSUE THREAD

**Issue by georgebzhang** [sveltejs/prettier-plugin-svelte#117]
{#each items as item}
  {item}
{/each}

gets automatically formatted (Option + Shift + F) in VSCode to

{#each items as item}{item}{/each}

Would much prefer if the auto formatter did not compress the each loop to a single line.

OS: Macbook Pro 2018
IDE: VSCode
Plugin/Package: Svelte for VSCode

Requested to forward this issue to prettier-plugin-svelte: https://github.com/sveltejs/language-tools/issues/451

**Comment by bholtbholt** [comment]
This occurs in Sublime Text 3 as well

**Comment by dummdidumm** [comment]
A workaround is to add `<!-- prettier-ignore -->` above the `{#each..`:

```html
<!-- prettier-ignore -->
{#each items as item}
    {item}
{/each}
```
