### ISSUE TITLE
style.css error in console (on development) - but seems not affecting anything

### ISSUE THREAD

**Issue by x4080** [sveltejs/prettier-plugin-svelte#124]
Hi, using the template, when I look at chrome console appears :

```
GET http://localhost:3000/dist/static/style.css net::ERR_ABORTED 404 (Not Found)
```

Is the style.css should be manually put inside public/dist/static folder ?

And for example I wanted to add a global.css, are the steps below correct ?
1.  Put global.css inside \src\assets
2.  Edit Layout.svelte and add line

```
<link rel="stylesheet" href="{settings.locations.assets.replace('./public', '')}global.css" />
```

The reason I'm asking because it will display error like above, but now with global.css
```
GET http://localhost:3000/dist/static/global.css net::ERR_ABORTED 404 (Not Found)
```

**Comment by x4080** [comment]
It seems if I put the global.css in the public/dist/static the error is gone and css applied correctly in development

So I should put it inside public/dist/static and for all needed assets ?

Thanks

**Comment by dummdidumm** [comment]
I think you opened this issue in the wrong repo, do you meant to open it in sveltejs/template?

**Comment by x4080** [comment]
@dummdidumm Sorry my mistake

**Comment by dummdidumm** [comment]
No worries, just open it in the correct repo, I'm going to close this one.
