### ISSUE TITLE
prettier-plugin-svelte@1.1.1" has unmet peer dependency "prettier@^1.16.4 || ^2.0.0"

### ISSUE THREAD

**Issue by Valexr** [sveltejs/prettier-plugin-svelte#128]
prettier-plugin-svelte@1.1.1" has unmet peer dependency "prettier@^1.16.4 || ^2.0.0"

**Comment by dummdidumm** [comment]
A little more context please. In what context are you using it? Have you installed prettier?

**Comment by Valexr** [comment]
it’s only warning on yarn upgrade

**Comment by dummdidumm** [comment]
Well this warning means that you don't have prettier installed. Install it if you want the warning to go away.
