### ISSUE TITLE
Prettier removes content from script block

### ISSUE THREAD

**Issue by mhatvan** [sveltejs/prettier-plugin-svelte#129]
When I use this fenced code block snippet in a markdown file and save the file

````markdown
```svelte
<style>
  h1 {
    color: green;
  }

  p {
    font-style: italic;
  }
</style>

<script>
  let role = "developer";
</script>

<h1>Hello, {role}!</h1>

<p>I hope you are having a good day!</p>

```
````

it removes the content of the `<script>` block and changes it to 

```
<script 1>

</script>
```

Not sure if this is related to `prettier-plugin-svelte` but it makes it impossible to use fenced code blocks with svelte, one workaround is to use html as code block language instead.

**Comment by dummdidumm** [comment]
Prettier passes a property `originalText`. This property is the preprocessed content in case the Svelte parser is called directly, in case of embeds it's the unpreprocessed text. This feels like a bug upstream.
