### ISSUE TITLE
Formatting does not match prettier config settings

### ISSUE THREAD

**Issue by JamesCoyle** [sveltejs/prettier-plugin-svelte#136]
I have a custom prettier config which defines my prefered style rules (tabs for indentation etc) but no matter what I do I can't seem to get the formatting to work. I initially tried the Svelte language extension for VSCode which I believe uses this plugin for formatting. I then tried installing prettier manually and configuring it with this plugin to run from the command line. Both seem to format with the default prettier config completely ignoring my preferences. 

Does this plugin ignore the prettier config? If so that seems really stupid.

**Comment by Conduitry** [comment]
No, it does not ignore the prettier config. GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
