### ISSUE TITLE
Always move component documentation comment to the top

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/prettier-plugin-svelte#137]
You can create documentation for a Svelte component [like this](https://svelte.dev/faq#how-do-i-document-my-components). I think it makes sense to always have this at the top of the file. 

Current result when using `scripts-markup-style`:

```html
<script>
  export let name = 'world';
</script>

<!--
@component
Here's some documentation for this component.
It will show up on hover.
-->
<h1>Hello, {name}</h1>

<style>
   h1 {
     color: blue;
   }
</style>
```

Desired result:

```html
<!--
@component
Here's some documentation for this component.
It will show up on hover.
-->

<script>
  export let name = 'world';
</script>

<h1>Hello, {name}</h1>

<style>
   h1 {
     color: blue;
   }
</style>
```

This would be a breaking change.

Thoughts?

**Comment by benmccann** [comment]
I think I like this change though I've never used this component documentation, so take that with a grain of salt. We should probably update the faq question you linked to if this change is made to use the same style.

**Comment by ehrencrona** [comment]
I would support this, but only for comments that actually do contain `@component`

Other top-level comments I believe should just stay where ever the author put them (i.e. in the example above the comment would be first only if it was originally put before the `<script>` element). Currently, they are re-ordered if you try to add a comment on e.g. the `<style>` tag.

If we reorder all comments it wouldn't be possible to comment on the top-level HTML-tag, e.g.

```
<script>
...
</script>

<!-- the "myprop" attribute is defined in a plugin -->
<h1 data-myprop>Title</h1>
```

**Comment by dummdidumm** [comment]
Only the `@component` comment would be reordered.

Your comment about "other comments are reorded" got me thinking though. Maybe we don't even need this kind of special behavior if we try to leave comments at its original place instead.

**Comment by ehrencrona** [comment]
@dummdidumm I agree; that would indeed seem most transparent. Also, my memory is the size of a turtle's; since #130 the comments should already stay in place; I was testing using an old version. So maybe nothing needs to be done after all?

**Comment by dummdidumm** [comment]
Unfortunately not, only a `prettier-ignore` comment stays where it is, other comments are moved to the markup part.

**Comment by ehrencrona** [comment]
Oh, right, true. We'd need to extend that to work with arbitrary comments then essentially. Looking at the code, that would also make sense code-wise. Seems like it should be a simple change.
