### ISSUE TITLE
Pretter is replacing HTML markup in <svelte:head> when Formatting on Save

### ISSUE THREAD

**Issue by ejoflo** [sveltejs/prettier-plugin-svelte#149]
There is a string of markup inserted by Prettier when I am attempting to save one of my Svelte components.  I am running the following extensions:

Svelte for VS Code 102.1.0
Prettier - Code formatter 5.7.1

I also have the svelte.svelte-vscode selected in settings under Edtior: Default Formatter

Here is the original markup:
![Screen Shot 2020-09-29 at 10 25 16 PM](https://user-images.githubusercontent.com/51680874/94661367-a8824800-02a2-11eb-91a3-b6a0f8e1c3ea.png)

When I attempt to save using the built-in "Format on Save" option using the latest Svelte Tools and Prettier, the following markup is inserted:

![Screen Shot 2020-09-29 at 10 23 21 PM](https://user-images.githubusercontent.com/51680874/94661329-9c968600-02a2-11eb-8277-fa481b74e1b0.png)

**Comment by ehrencrona** [comment]
Could you please post the complete content of a `.svelte` file that triggers this behavior as text?

**Comment by ejoflo** [comment]
Is it possible to post this code privately? Unfortunately I don't have permission from the client to share the codebase publicly.

**Comment by ehrencrona** [comment]
I’d only need a single file where the issue occurs. If you can strip it down to the minimum needed for it to happen, that’s great. Feel free to replace any text or code or whatever might be sensitive.

**Comment by dummdidumm** [comment]
We just need a minimum reproducible that is copy-pasteable, not the whole file or the whole project.

**Comment by ejoflo** [comment]
Okay, the code I posted in the image above can reproduce the bug.  Just paste it into VS Code and either press Alt(Option)+Shift+F to format or enable Format on Save in the settings.  I just tested this.  If you need more I can strip it down further but this alone appears to be enough to trigger the bug.

`
<svelte:head>
  <style>
    body {
      overflow: hidden;
    }
  </style>
</svelte:head>`

**Comment by ehrencrona** [comment]
I can't reproduce the issue; the file formats fine for me (svelte extension 102.1.0). Weird.

**Comment by ejoflo** [comment]
This is what my .prettierrc looks like. I wonder if it would make a difference?

```
{
  "svelteStrictMode": true,
  "svelteSortOrder": "scripts-markup-styles",
  "tabWidth": 2,
  "singleQuote": true,
  "jsxSingleQuote": true,
  "arrowParens": "always"
}
```
