### ISSUE TITLE
HTML comments inside svelte markup cause formatting to fail

### ISSUE THREAD

**Issue by marcusnewton** [sveltejs/prettier-plugin-svelte#151]
**Describe the bug**
HTML comments inside svelte markup prevents remaining markup from being formatted.

**To Reproduce**
For example (with `"svelteStrictMode": true`) this:

```svelte
<Component   foo={bar} 
      />
<!-- comment -->
<Component   foo={bar} 
      />
```
becomes
```svelte
<Component foo="{bar}" />
<!-- comment -->
<Component   foo={bar} 
      />
```

<hr/>

Using js comments works, however, they are not syntax highlighted.

```svelte
<Component foo="{bar}" />
// comment
<Component foo="{bar}" />
```

**Expected behavior**
Should get this:
```svelte
<Component foo="{bar}" />
<!-- comment -->
<Component foo="{bar}" />
```

**System:**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: "Svelte for VSCode"

**Comment by dummdidumm** [comment]
Transfered to `prettier-plugin-svelte` repo.

**Comment by ehrencrona** [comment]
@ljonya Could you please create a new ticket for the issue you're reporting (in `prettier-plugin-svelte`)? It sounds like something unrelated to this ticket which is about comments preventing part of the file from being formatted. Please include (in text format) a file that formats wrongly. It tried adding a comment to https://github.com/sveltejs/sapper-template/blob/master/src/routes/blog/index.svelte as you described and was unable to reproduce it.

**Comment by ljonya** [comment]
@ehrencrona Okay. I will make a repo with a project and describe the steps to reproduce it.
