### ISSUE TITLE
Prettier puts quotes around curly braces in HTML

### ISSUE THREAD

**Issue by martonlederer** [sveltejs/prettier-plugin-svelte#153]
Prettier turns 
```svelte
<Router routes={routes} />
```
to
```svelte
<Router routes="{routes}" />
```
I can't find a way to disable it. Any suggestions?

**Comment by dummdidumm** [comment]
Do you have `.prettierrc` config file? Is `svelteStrictMode: true` in there? If so, that's the reason. See the readme for more info.

**Comment by martonlederer** [comment]
Oh thanks, didn't see that
