### ISSUE TITLE
Is this plugin considered a parser?

### ISSUE THREAD

**Issue by ritchieanesco** [sveltejs/prettier-plugin-svelte#158]
We have the html parse override enabled in our prettier config. Now that we have installed this plugin, could we assume that this plugin can parse svelte files or would we still require the override?

**Comment by Conduitry** [comment]
Yes you should use this plugin directly as the parser/formatter for .svelte files, and not the .html one.

**Comment by dummdidumm** [comment]
I'm curious though, what were your overrides to get formatting working?
