### ISSUE TITLE
Include svelte:options in svelteSortOrder option

### ISSUE THREAD

**Issue by TobiasEmilHarbo** [sveltejs/prettier-plugin-svelte#165]
I am using svelte:options to convert my components into web components.
When running prettier the svelte:options gets moved together with the markup but with no line breaks:

```
<svelte:options tag="dxp-headline" />{#if !!data?.fields}
  <div class="container">
    {#each data.fields as field}
      <h2>{field.value}</h2>
    {/each}
  </div>
{/if}
```

It would be nice if this could be controlled with the svelteSortOrder option

**Comment by dummdidumm** [comment]
Not exactly a duplicate, but closing in favor of #73
