### ISSUE TITLE
Automatically lowercasing components in HTML

### ISSUE THREAD

**Issue by nathancahill** [sveltejs/prettier-plugin-svelte#166]
Given code like this:

```html
<Form></Form>
```
where `Form` is a Svelte component, prettier-plugin-svelte outputs:

```html
<form></form>
```

This happens when any Svelte component name matches a HTML tag.

**Comment by dummdidumm** [comment]
I am not able to reproduce this. Are you using the latest version? Do you have a `.prettierrc` config, and if so, what's in it? Do you format through the Svelte for VS Code extension or through the prettier cli?

**Comment by dummdidumm** [comment]
Closing due to lack of reproduction.
