### ISSUE TITLE
How can i make this work with the nova editor from panic?

### ISSUE THREAD

**Issue by benjamin79** [sveltejs/prettier-plugin-svelte#168]
Hi,

panics new editor (coda 3) nova is out since a while. (https://nova.app/) Prettier is supported with a plugin. How can i make the svelte part working?

thanks

**Comment by Conduitry** [comment]
I've never heard of this editor, but it looks like https://extensions.panic.com/extensions/alexanderweiss/alexanderweiss.prettier/ tells you how to use Prettier plugins.

GitHub issues aren't the right place for support questions like this. Please ask in our [Discord chat room](https://svelte.dev/chat) if you have questions.
