### ISSUE TITLE
[feat] Break down big prop objects into separate lines

### ISSUE THREAD

**Issue by dkzlv** [sveltejs/prettier-plugin-svelte#170]
**Is your feature request related to a problem? Please describe.**
Currently prettier plugin does not break down big props/objects into multiple lines if it is placed in template. More than that, it puts everything into one huge line, ignoring the `printWidth` setting.

**Describe the solution you'd like**
It should work exactly like it does in other places.

Take this code as an example:

```svelte
<input
  class="input"
  type="password"
  bind:value={$passwordStore.rawValue}
  use:trackChanges={{ store: passwordStore, clean: [ensureString], validate: [minLength(6), maxLength(25)] }} />
  // Cannot be broken down into multiple lines no matter what
```

It should be formatted into something like this:

```svelte
<input
  class="input"
  type="password"
  bind:value={$passwordStore.rawValue}
  use:trackChanges={{
    store: passwordStore,
    clean: [ensureString],
    validate: [minLength(6), maxLength(25)]
  }} />
```

**Comment by dummdidumm** [comment]
Fixing this is easy. The only question is, do we want to change this behavior for everything? I think the only question is whether we want to have that for svelte control blocks, too. It may then look like this:

```svelte
<p>
  asdddddddddddddddddddddddddddddddddddddddd{#await Promise.resolve(
         "asd"
     ) then b}s{/await}
</p>
```

@Conduitry @ehrencrona what do you think?

**Comment by ehrencrona** [comment]
I’d say it’s reasonable to do it in control blocks, too, but I’m not sure I can overview all the consequences. 
But it feels like in most situations, if you don’t like how it breaks, you can just put the tag (`await` in your example) on a new line, so it’s no so close to the max width.

**Comment by dummdidumm** [comment]
After some more thought I think it's better to not break up control blocks. In the case of if/else they might contain destructurings/arrays which would look really clunky broken up. So I'd say break everything except control blocks.
