### ISSUE TITLE
Inconsistent quote format

### ISSUE THREAD

**Issue by pushkine** [sveltejs/prettier-plugin-svelte#189]
input :
```svelte
<script lang="ts">
     const bar = "foo";
</script>

<div use:action={"foo"} />
```
output :
```svelte
<script lang="ts">
	const bar = "foo";
</script>

<div use:action={'foo'} />
```

**Comment by dummdidumm** [comment]
Duplicate of #94, fixed since `2.0.0`. You likely don't see this change yet because the VS Code extension comes prepackaged with a pre-`2.x` version. Will update that one soon.
