### ISSUE TITLE
prettier-plugin-svelte@2.1.0" has unmet peer dependency "prettier@^1.16.4 || ^2.0.0"

### ISSUE THREAD

**Issue by Valexr** [sveltejs/prettier-plugin-svelte#192]
on install modules...

`prettier-plugin-svelte@2.1.0" has unmet peer dependency "prettier@^1.16.4 || ^2.0.0"`

**Comment by dummdidumm** [comment]
You opened  that same issue before in #128. My questions stay the same: Do you have the `prettier` package installed in the correct version? If not, that's expected. I need more details from you, like your `package.json` contents.

**Comment by Valexr** [comment]
Yep 🤓 tx & sorry for repeat.
With prettier 2.1.1 all good. But prettier integrated in VScode... I think old version eat...

**Comment by dummdidumm** [comment]
If you don't have `prettier` in your `package.json` it will not be in your `node_modules` and therefore npm will issue the warning because it cannot find `prettier`. So the warning is correct and you can choose to ignore it if it works for you.
