### ISSUE TITLE
Is there an option to always wrap {#if}, {:else} and {/if} to new lines?

### ISSUE THREAD

**Issue by AlexGalays** [sveltejs/prettier-plugin-svelte#201]
Title.

Right now, we often end up with unreadable code.

Example of currently poorly formated code (and that's a simple if/else condition even):
![image](https://user-images.githubusercontent.com/1375586/106970354-f6292880-674c-11eb-8e45-ec54368c2274.png)

What i'd like:
![image](https://user-images.githubusercontent.com/1375586/106970334-ee698400-674c-11eb-87c1-d6060147104e.png)

Cheers

**Comment by dummdidumm** [comment]
Since version 2 of this plugin, you can format this "by hand" as shown in screen two and the plugin will not format this back into one line. It will not do this automatically because of whitespace. `{#if true}hi{/if}there` will print `hithere` whereas 
```
{#if true}
  hi
{/if}there
```
will print `hi there`.

**Comment by AlexGalays** [comment]
Ah, should have checked the more recent versions instead of the github issues.

Many thanks for this.
