### ISSUE TITLE
Don't append trailing newline when parsing markdown code blocks

### ISSUE THREAD

**Issue by thislooksfun** [sveltejs/prettier-plugin-svelte#202]
Every other code block formatter (tested with `ts`, `js`, and `html`) leaves the fenced code blocks with no trailing newlines, but this one appends a trailing newline, which is therefore out of place and distracting. It would be great if this could leave 0 trailing newlines in these fenced blocks.

EDIT: namely, remove line 20 of test/printer/samples/markdown.md.

**Comment by thislooksfun** [comment]
@dummdidumm Thanks for the quick fix!  Unfortunately it doesn't seem to be working in the wild (https://github.com/thislooksfun/svelte-repo-card @ README.md#73-81). Any ideas why it's not working for me?

**Comment by dummdidumm** [comment]
Thanks for the update, there was a situation the test did not catch, new release pending.

**Comment by dummdidumm** [comment]
Released

**Comment by thislooksfun** [comment]
That worked beautifully, thank you!
