### ISSUE TITLE
HTML comment is duplicated when using Format on Save

### ISSUE THREAD

**Issue by ejoflo** [sveltejs/prettier-plugin-svelte#205]
When enabling "Format on Save" in VS Code settings, recently I've noticed that some comments are being duplicated on save. Here are two images:

Before:
![Screen Shot 2021-02-14 at 9 42 46 AM](https://user-images.githubusercontent.com/51680874/107887318-5cc6e880-6ea9-11eb-8318-4d40408bc00a.png)

After:
![Screen Shot 2021-02-14 at 9 43 00 AM](https://user-images.githubusercontent.com/51680874/107887320-618b9c80-6ea9-11eb-83c5-f198c221c051.png)

I didn't have this issue before and I can only prevent it by disabling "Format on Save" or unchecking "Format: Enable" in Settings under Extensions > Svelte.

**Comment by dummdidumm** [comment]
This was released in the VS Code extension version 104.4.2

**Comment by behicsakar** [comment]
```
"prettier": "^2.8.0",
"prettier-plugin-svelte": "^2.10.1",
```
https://github.com/sveltejs/prettier-plugin-svelte/assets/3280475/33e9077f-99a3-43a7-904b-0fdef4f3860c

**Comment by icjosh10** [comment]
> ```
> "prettier": "^2.8.0",
> "prettier-plugin-svelte": "^2.10.1",
> ```
> 
>  prettier.mp4

I'm experiencing the exact same thing
