### ISSUE TITLE
printWidth ignored for object attributes

### ISSUE THREAD

**Issue by felixakiragreen** [sveltejs/prettier-plugin-svelte#230]
When attributes contain object that are longer than the printWidth, they **should** be split-up, this is what they do in normal React JSX/TSX when formatting with Prettier.

Example code:
```
<Stack align="leading" space="md" css={{
	py: '$12',
	'@initial': {
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'center',
		px: '$1',
	},
	'@md': {
		height: 'calc(100vh - 80px)',
		alignItems: 'start',
		textAlign: 'left',
	},
}}>
```

However, in Svelte files, prettier reformats these to all being on the same line, resulting in this:
```
<Stack
	align="leading"
	space="md"
	css={{ py: '$12', '@initial': { alignItems: 'center', justifyContent: 'center', textAlign: 'center', px: '$1' }, '@md': { height: 'calc(100vh - 80px)', alignItems: 'start', textAlign: 'left' } }}
>
```

You can see a video of this happening here:

https://user-images.githubusercontent.com/1843672/119083353-d18c5000-b9cd-11eb-96e6-0e3548364cc5.mov

**Comment by dummdidumm** [comment]
I can't reproduce this. Are you using the latest version of the plugin?

**Comment by felixakiragreen** [comment]
Figured it out. I was using https://github.com/SimonSiefke/prettier-vscode — by switching to https://github.com/prettier/prettier-vscode it works correctly now.
