### ISSUE TITLE
Max number of props per line setting

### ISSUE THREAD

**Issue by Sluggern** [sveltejs/prettier-plugin-svelte#234]
Hello!

Are there any plans to implement a setting controlling the maximum number of props per line? Something like the Prettier plugins for [React](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-max-props-per-line.md) and [Vue](https://eslint.vuejs.org/rules/max-attributes-per-line.html) has? I would really like that 🥇 

Anyway, thanks!

**Comment by dummdidumm** [comment]
These are ESLint rules, this repo deals with Prettier code formatting. You need to open that feature request at [eslint-plugin-svelte3](https://github.com/sveltejs/eslint-plugin-svelte3)

**Comment by Sluggern** [comment]
My bad, thanks!
