### ISSUE TITLE
HTML whitespace is not maintained.

### ISSUE THREAD

**Issue by hperrin** [sveltejs/prettier-plugin-svelte#24]
Wrapping a word just before punctuation, but not wrapping the punctuation, results in bad formatting.

```html
<p>This is a <strong>bold stance</strong>.</p>
```
becomes

```html
<p>
  This is a
  <strong>bold stance</strong>
  .
</p>
```

Which is rendered as:

This is a **bold stance** .

Notice the space before the period.

**Comment by RedHatter** [comment]
One work around for this issue is to use a markup preprocessor on compilation to remove all white-space.

```
    svelte({
      preprocess: {
        markup: input => ({
          code: input.content
            .replace(/(>|})\s+(?![^]*?<\/(?:script|style)>|[^<]*?>|[^{]*?})/g, '$1')
            .replace(/(?<!<[^>]*?|{[^}]*?)\s+(<|{)(?![^]*<\/(?:script|style)>)/g, '$1')
        })
      },
      css: css => css.write('dest/devtools/styles.css'),
    })
```

**Comment by jarrodldavis** [comment]
Hey @hperrin, I've begun working on fixing this in #41. Please let me know if you think this is an adequate fix.

**Comment by happycollision** [comment]
Ugh. I tried to take over #41 by cloning, but I cannot figure it out quickly enough to be worthwhile. No Prettier for me, I suppose.

**Comment by terrygonguet** [comment]
This is still a problem and #41 seems to have been abandonned...
Similarly to @happycollision I tried to jump into it but there's too much to take in alone.
However this particular issue seems to have been fixed at some point in #41, could we not "just" get that part merged into master? I understand the other goals of the PR are important too but why not use a fix we already have?

**Comment by happycollision** [comment]
That was my original intent: to fork and just do a smaller PR, but even the state that it was in already did not seem to fix the inline element whitespace issue.

**Comment by louisabraham** [comment]
Hi, I have the same problem even with option `--html-whitespace-sensitivity=strict`

**Comment by elbertwang3** [comment]
also having this issue. are there any workarounds?

**Comment by vrde** [comment]
Hi, unfortunately this makes the plugin unusable :cry: any plan to address this?

**Comment by ehrencrona** [comment]
My PR #116 should fix this.
