### ISSUE TITLE
Incorrect formatting when using custom elements

### ISSUE THREAD

**Issue by Zettexe** [sveltejs/prettier-plugin-svelte#245]
**Describe the bug**
Formatting for long lines doesn't work correctly when using custom elements

**Expected behavior**
tag should be formatted the same way as div

**Screenshots**
![image](https://user-images.githubusercontent.com/53223513/129480733-76b7f821-21fb-416f-8659-3546dd5db367.png)

**System (please complete the following information):**
 - OS: Windows
 - IDE: VSCode
 - Plugin/Package: Svelte for VSCode

**Comment by dummdidumm** [comment]
This the correct behavior. It is not known to prettier whether or not the custom element's content is whitespace sensitive. If it was it means that a leading/trailing whitespace or newline make a difference in appearance. You can add a whitespace yourself at the start and end and it would then format the same way as the div.

**Comment by Zettexe** [comment]
Surely there should be a way to configure this right? In this example I used <tag> however I am currently using Ionic Framework which relies heavily on custom elements and its quite an annoyance to add whitespaces each time on all the same tags.

**Comment by dummdidumm** [comment]
https://prettier.io/docs/en/options.html#html-whitespace-sensitivity this will then affect all tags
