### ISSUE TITLE
svelteSortOrder is missing option `options`. This will be an error in prettier-plugin-svelte version 3.

### ISSUE THREAD

**Issue by rjpruitt16** [sveltejs/prettier-plugin-svelte#252]
☁  frontend [main] ⚡  ls -a     
.                   .routify            netlify.toml        postcss.config.js   src
..                  README.md           node_modules        rollup.config.js    tailwind.config.js
.nolluprc.js        api                 package-lock.json   sandbox.config.json tsconfig.json
.prettierrc.json    assets              package.json        secrets.env         vercel.json
☁  frontend [main] ⚡  

☁  frontend [main] ⚡  cat .prettierrc.json 
{
    "arrowParens": "avoid",
    "bracketSpacing": true,
    "printWidth": 80,
    "semi": true,
    "singleQuote": false,
    "tabWidth": 4,
    "trailingComma": "all",
    "svelteSortOrder": "styles-scripts-markup",
    "svelteStrictMode": true,
    "svelteBracketNewLine": true,
    "svelteAllowShorthand": true,
    "plugins": ["prettier-plugin-svelte"]
}

**Comment by ignatiusmb** [comment]
Please read https://github.com/sveltejs/prettier-plugin-svelte#svelte-sort-order

**Comment by rjpruitt16** [comment]
May you show me an example? I keep reading the description, but I am still lost.

**Comment by rjpruitt16** [comment]
Never mind, I figure it out

{
    "arrowParens": "avoid",
    "bracketSpacing": true,
    "printWidth": 80,
    "semi": true,
    "singleQuote": false,
    "tabWidth": 4,
    "trailingComma": "all",
    **"svelteSortOrder": "options-styles-scripts-markup",**
    "svelteStrictMode": true,
    "svelteBracketNewLine": true,
    "svelteAllowShorthand": true,
    "plugins": ["prettier-plugin-svelte"]
}
