### ISSUE TITLE
allow comments after style

### ISSUE THREAD

**Issue by basaran** [sveltejs/prettier-plugin-svelte#258]
Hello, thank you for this plugin. I have one small issue as it can be seen from the clip below. I like to make my code more beautiful by using comment blocks with nice ascii arts in place.

https://user-images.githubusercontent.com/30809170/138387483-37c30163-8d44-4ab2-80c0-d5b2df268d74.mp4

When I save the file, svelte plugin's reordering mechanism kicks in and shifts Bart footer.

And it also effectively removes any spacing when such shift occurs.

https://user-images.githubusercontent.com/30809170/138387945-dab45a35-3a24-4b43-9cc0-7e23078ec5e2.mp4

It would be better if there was a work around to handle comments blocks.

P.S I'm on sublime.

**Comment by basaran** [comment]
I just noticed that :)

**Comment by Conduitry** [comment]
I'm transferring this from the ESLint plugin repository to the Prettier plugin repository, because the ESLint plugin doesn't do any reordering like this.

**Comment by basaran** [comment]
I know, I was about to close but you acted too fast. Thank you.

**Comment by dummdidumm** [comment]
With #314 implemented you can chose `svelteSortOrder: none` which allows you to have comments anywhere you want without them being reordered - closing.
