### ISSUE TITLE
Svelte Bracket New Line (3rd option)

### ISSUE THREAD

**Issue by RomanistHere** [sveltejs/prettier-plugin-svelte#270]
Hi, here we can check how _**bracket new line**_ works: https://github.com/sveltejs/prettier-plugin-svelte#svelte-bracket-new-line

However, am I the only one who doesn't find this code pretty or understandable? 

```
<span
    ><div>foo</div>
    <span>bar</span></span
>
<div
     pretend
     break
>
    content
</div>
```

Svelte is more HTML than JSX or other template syntaxes, so I'd like to see it more HTML-like formatted. I might have missed some best practices, but there still should be a room (option) for something like this:

```
<span>
    <div>foo</div>
    <span>bar</span>
</span>
<div
     pretend
     break
>
    content
</div>
```

I'd considered everything-from-the-new-string over current formatting:

```
<span>
    <div>
        foo
    </div>
    <span>
        bar
    </span>
</span>
<div
     pretend
     break
>
    content
</div>
```

Is there a way to achieve it right now?

**Comment by dummdidumm** [comment]
[Read this](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) on why this happens. You can adjust whitespace sensitivity through [this setting](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity).
