### ISSUE TITLE
Unit test fail

### ISSUE THREAD

**Issue by ShroXd** [sveltejs/prettier-plugin-svelte#277]
# Context

I tried to run the unit test of this repo, but the test case for _svelte_ is fail. Look like it's because we can't import the svelte/compiler, but I don't know how to address this problem.

# Screenshot

![image](https://user-images.githubusercontent.com/48713853/155663143-66d13887-7720-4a1d-8a6e-8bd3df944967.png)

**Comment by dummdidumm** [comment]
Please provide more details. What tests are you referring to? Is there a repository to look at? How does the package.json look like?

**Comment by ShroXd** [comment]
> Please provide more details. What tests are you referring to? Is there a repository to look at? How does the package.json look like?

Sorry.. I realize I put the issue in the wrong repo😰
