### ISSUE TITLE
Enable just the quoting behavior from strict mode

### ISSUE THREAD

**Issue by ohmree** [sveltejs/prettier-plugin-svelte#279]
Given the following example:
```svelte
<input {value} on:input="{(ev) => console.log(ev.currentTarget.value)}" />
```
Formatting with strict mode turned off will result in the following output:
```svelte
<input {value} on:input={(ev) => console.log(ev.currentTarget.value)} />
```
While having it on will result in the following output:
```svelte
<input value="{value}" on:input="{(ev) => console.log(ev.currentTarget.value)}" />
```
Now my editor plugin that handles svelte syntax highlighting (emacs web-mode) is an ungodly mess of spaghetti code and regexes and doesn't like unquoted curly braces so I'd like to enforce quotes around them, while still using shorthand attributes and self-closing tags where strict mode wouldn't allow them.
Can an option be added that enables just the quoting behavior from strict mode?

**Comment by dummdidumm** [comment]
In version 3, the shorthand setting will take precedence over strict mode.
