### ISSUE TITLE
prettier-plugin-jsdoc supports

### ISSUE THREAD

**Issue by hosseinmd** [sveltejs/prettier-plugin-svelte#280]
I want to support jsdoc formatting for svelte, but don't have enough knowledge for about svelte. Could we start it with some help from you?

**Comment by dummdidumm** [comment]
I'll try to explain what a Svelte file consists of, let's see how far we can get. I'll answer in https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/151 , so let's move the discussion to that issue.
