### ISSUE TITLE
Disable self-closing tag if empty

### ISSUE THREAD

**Issue by lacherogwu** [sveltejs/prettier-plugin-svelte#284]
### Describe the bug

Hello, 

I think when the html tag is empty, it should use self-closing on format.
<img width="386" alt="image" src="https://user-images.githubusercontent.com/49835614/162388932-579712b1-6a35-4a57-af74-84534455794b.png">

When I'm writing code, sometimes I write just boilerplate of HTML tags before I implement any styles and it's kinda annoying that it's closing empty elements, and to be honest it doesn't really make sense...

If the tag is not empty and contains any attribute so I believe self-closing will be the right way to go
for e.g.
```
<div class="a" /> ✅
<div /> ❌
<div></div> ✅
```

Thanks!

### Reproduction

Write any HTML tag and save the file
I use Prettier for formatting, and auto-format on save

### System Info

```shell
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
    Memory: 2.86 GB / 48.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 98.0.2
    Firefox Developer Edition: 98.0
    Safari: 13.1.1
  npmPackages:
    svelte: ^3.44.0 => 3.46.6
```

### Severity

annoyance

**Comment by khaki32** [comment]
I agree. In fact I'd prefer the option to completely self closing tags for plain HTML elements. It even self-closes auto-closing tags like `<br>` or `<input>`. I think it makes the code actually uglier.

**Comment by JounQin** [comment]
I think html compliant should be preferred like prettier core and we can adopt the core option.

**Comment by ajikia15** [comment]
Have you fixed the issue somehow?

**Comment by dummdidumm** [comment]
In `prettier-plugin-svelte` version 3 tags will be left as-is.
