### ISSUE TITLE
HTML elements brake into multiple lines

### ISSUE THREAD

**Issue by veniplex** [sveltejs/prettier-plugin-svelte#294]
Hey, I don't find any way to prevent prettier from formatting this:
```
<nav class="flex h-full min-h-[70px] items-center justify-between bg-primary px-7 text-secondary">
```
to this:
```
<nav
  class="flex h-full min-h-[70px] items-center justify-between bg-primary px-7 text-secondary">
```

I have created a `.prettierrc` file with the following settings:
```
{
  "svelteBracketNewLine": false
}
```

but this does only change the behavior of the closing `>`. What am I missing?

**Comment by veniplex** [comment]
Okay I just found out that once you configured `svelteBracketNewLine` the plugin will ignore `prettier:printWidth`. Is this intended? (This is the first time I am using a prettier plugin...)

**Comment by dummdidumm** [comment]
This works as expected. Prettier tries to break lines that are longer than the character with into multiple lines at positions where it can break, and this is a position where it can do a new line, so it does do that. You see the same behavior when formatting a HTML file with Prettier.
