### ISSUE TITLE
The new `singleAttributePerLine` option not working

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/prettier-plugin-svelte#305]
Prettier added a [`singleAttributePerLine` option](https://prettier.io/docs/en/options.html#single-attribute-per-line) in version 2.6.0, which applies to any kind of markup including the HTML in `.svelte` files, but it seems like enabling it has no effect when formatting Svelte files:

https://user-images.githubusercontent.com/26527405/189521387-1effab32-155d-44ba-9d59-f30704e4f562.mp4

**Comment by dummdidumm** [comment]
It's an enhancement because we don't use the HTML/JSX parser of Prettier which supports this now, we have to create our own. So it's an enhancement because it's a new option which wasn't added support for yet.

**Comment by dummdidumm** [comment]
Because the HTML parser would parse things like `{#if ...` or `{foo}` as a regular string, and get confused at things like `<div on:click={() => ..}`
