### ISSUE TITLE
Option to disable offset of the top level script tag

### ISSUE THREAD

**Issue by IlyaSemenov** [sveltejs/prettier-plugin-svelte#31]
Considering this code:

```html
<script>
	export const foo = 123
</script>

<h1>foo = {foo}</h1>
```

can there be at least the option to disable indentation of the script? It looks awful especially in complex components, where like 80% of code becomes indented for no reason.

prettier itself defaults to **not** indent first-level SFC tags (https://github.com/prettier/prettier/issues/3888).

**Comment by UnwrittenFun** [comment]
Technically prettier does default to indenting when parsing as html (See [playground example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wB8AOlHAB54RYwAEkU6dAZhBLQLy0CMATAMylUAeky4CJKEIAW3Qq3ZdgCgL4jZhEABoQEAjmjpkoAIZYsEAO4AFMwiMoTANwg4AJtpAAjLCbABrOBgAZTw-HCgAc2QYLABXOB1pGABbABsAdWkceHQwsDhg+xycJxyAT2RwdCMdCPQ4GmtfSJSTZGYTNIadACt0cgAhXwCg4JMUuAAZCLgOrp6QfvJgiMi0uABFOIh4ee7EkDCsBqwq5PTPPFxYDPcYaWQADgAGHWuIBozfPCrruFOTjmOgAjjt4M09A4QCZ0ABaMhwNxIzxYOBgnBo5omVrtJCdA46BopHAxeKHdBrDbbXZzfELQ4wExeO5uB7IXg6WImHBpNYAYQgKTaVSg0GBIDiDQAKsyHASGioVEA)) and seeing as the standard use by svelte throughout the docs is to indent I'm inclined to leave it like this without significant support for without
