### ISSUE TITLE
Svelte @component documentation is sorted by svelteSortOrder

### ISSUE THREAD

**Issue by PeytonHanel** [sveltejs/prettier-plugin-svelte#319]
Hello,

Depending on the svelteSortOrder, the @component documentation is also sorted. Since this is meant to document the entire component, it should always be at the top of the file where developers can easily see it.

![image](https://user-images.githubusercontent.com/26446761/201180249-c5dd9003-f83d-4977-a06e-10e08ebe9ed4.png)

There should either be a feature enabling/disabling this sorting or it should not be included.

I am using v2.8.0

Thank you.

**Comment by dummdidumm** [comment]
There is a feature to disable sorting for these sorts of use cases: `svelteSortOrder: "none"`, therefore closing this.

In your case you could also make it work by moving that "xl breakpoint defines .." comment to second position. The comment above the script tag will be kept above it when reordering.
