### ISSUE TITLE
prettier: command not found after following installation instructions

### ISSUE THREAD

**Issue by alexspurling** [sveltejs/prettier-plugin-svelte#322]
I followed the installation instructions in the readme by running:

```
npm i --save-dev prettier-plugin-svelte prettier
```

After this I typed:

```
prettier
```

But this gives: `prettier: command not found`

Are the instructions incomplete?

**Comment by Conduitry** [comment]
Perhaps the documentation could be made clearer. But this is how all npm packages work though. It creates a binary in `node_modules/.bin`, not on your path. You can run `prettier` with https://docs.npmjs.com/cli/v9/commands/npx
