### ISSUE TITLE
Top-level `<script>` tag formatted incorrectly

### ISSUE THREAD

**Issue by g-plane** [sveltejs/prettier-plugin-svelte#344]
## Version

Prettier: v2.8.3
prettier-plugin-svelte: v2.9.0

## Input

Attribute value without quotes.

```svelte
<script lang=ts></script>
```

## Actual Output

The `=` char is removed.

```svelte
<script lang ts></script>
```

## Expected Output

It should add quotes, not remove the `=`.

```svelte
<script lang="ts"></script>
```

I can provide more detail if you need.

**Comment by Rolaka** [comment]
Tried to fix the regex, tested against some examples.
```
attr=value
['attr=value', 'attr', null, 'value']

attr="value"
['attr="value"', 'attr', '"', 'value']

attr='value'
["attr='value'", 'attr', "'", 'value']

attr
['attr', 'attr']
```
