### ISSUE TITLE
Lint error from HTML comments in svelte:head script/style

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/prettier-plugin-svelte#362]
In v2.10.0 there's a lint error for this:
```svelte
<svelte:head>
	<!-- Comment -->
	<script></script>
</svelte:head>
```

Every time you run `npm run format`, it duplicates the comment (but the lint error never disappears)

Reproduction:
1. `npm create svelte@latest`
2. Add the above code to `src/routes/+page.svelte`
3. `npm run lint`

**Comment by joshdales** [comment]
We just encountered this as well. It only seems to happen when you a comment that is followed by a script tag. If you have a `title` or whatever else its fine.

**Comment by probablykasper** [comment]
Seems to be fixed in v3
