### ISSUE TITLE
Wired formats with `svelteIndentScriptAndStyle` option in WebStorm

### ISSUE THREAD

**Issue by RoyRao2333** [sveltejs/prettier-plugin-svelte#375]
Here's my `.prettierrc.json`:

```json
{
  "trailingComma": "all",
  "tabWidth": 2,
  "printWidth": 80,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "quoteProps": "as-needed",
  "bracketSpacing": true,
  "arrowParens": "always",
  "endOfLine": "lf",
  "svelteSortOrder": "options-styles-scripts-markup",
  "svelteStrictMode": true,
  "svelteBracketNewLine": false,
  "svelteAllowShorthand": false,
  "svelteIndentScriptAndStyle": false,
  "tailwindConfig": "./tailwind.config.js",
  "plugins": ["prettier-plugin-svelte", "prettier-plugin-tailwindcss"],
  "overrides": [
    {
      "files": "*.svelte",
      "options": {
        "parser": "svelte"
      }
    }
  ]
}
```

Before formatting:

<img width="680" alt="image" src="https://github.com/sveltejs/prettier-plugin-svelte/assets/31413093/957fd8a4-a169-4938-b078-b355f38fba3c">

After formatting:

<img width="683" alt="image" src="https://github.com/sveltejs/prettier-plugin-svelte/assets/31413093/32f48b90-9819-4e11-bc06-010fc2af096a">

You can notice that codes in `<script>` tag lost indents. `<button>`'s props is also formatted wrong.

But if I remove `"svelteIndentScriptAndStyle": false` and format:

<img width="724" alt="image" src="https://github.com/sveltejs/prettier-plugin-svelte/assets/31413093/f019de26-ee99-48f0-bfcc-750fb61782c4">

Seems alright but I think the trailing `>` of `<button>` is supposed to be in a new line...

I'm new to Svelte and really love this framework. I came from React and I just copy & paste the `.prettierrc` from my previous React project and made some changes. Don't know if I set something wrong, any help would be appreciated!

**Comment by dummdidumm** [comment]
This works as expected:
- the indentation option set to false results in not indenting Script and Style tags at the root: https://github.com/sveltejs/prettier-plugin-svelte#svelte-indent-script-and-style
- the class attribute is not formatted currently so your can sort long classnames into as many lines as you please

Hope this clears things up - welcome to Svelte!

**Comment by RoyRao2333** [comment]
@dummdidumm 

Thanks for the explanations! Really helpful. :)

But as I described above, can I make the trailing `>` of `<button>` in a new line like this?

<img width="714" alt="image" src="https://github.com/sveltejs/prettier-plugin-svelte/assets/31413093/94b10f9e-e5f3-4fef-a287-b8ce96cb3de8">

I think this can separate component's attributes from the children (or slot?) within it and it's easy to read.

**Comment by dummdidumm** [comment]
For that, remove `"svelteBracketNewLine": false,` from your config

**Comment by RoyRao2333** [comment]
@dummdidumm 

It's working and thanks for the help! You truly saved my day!
