### ISSUE TITLE
Plugin is incorrectly rewriting empty non-void HTML tags in svelte files

### ISSUE THREAD

**Issue by Michael77** [sveltejs/prettier-plugin-svelte#377]
Within `.svelte` files, this plugin rewrites empty `<div></div>` to `<div />` which is an HTML error according to the whatwg spec:

[`non-void-html-element-start-tag-with-trailing-solidus`](https://html.spec.whatwg.org/multipage/parsing.html#parse-error-non-void-html-element-start-tag-with-trailing-solidus)

> This error occurs if the parser encounters a [start tag](https://html.spec.whatwg.org/multipage/syntax.html#syntax-start-tag) for an element that is not in the list of [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) or is not a part of foreign content (i.e., not an SVG or MathML element) that has a U+002F (/) [code point](https://infra.spec.whatwg.org/#code-point) right before the closing U+003E (>) code point.

The list of valid void elements:
[area](https://html.spec.whatwg.org/multipage/image-maps.html#the-area-element), [base](https://html.spec.whatwg.org/multipage/semantics.html#the-base-element), [br](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element), [col](https://html.spec.whatwg.org/multipage/tables.html#the-col-element), [embed](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-embed-element), [hr](https://html.spec.whatwg.org/multipage/grouping-content.html#the-hr-element), [img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element), [input](https://html.spec.whatwg.org/multipage/input.html#the-input-element), [link](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element), [meta](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element), [source](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element), [track](https://html.spec.whatwg.org/multipage/media.html#the-track-element), [wbr](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-wbr-element)

**Comment by dummdidumm** [comment]
We will adjust the options in the next major version to make this possible, though we're not sure yet what the default should be. Closely related to #238 .

**Comment by Michael77** [comment]
Please consider making the defaults align with the HTML standard as well as the behavior of prettier core.

Further, my initial motivation to report this issue was because I found it frustrating to write layout structure in HTML only to have several elements being rewritten as `<tag />` before I gave them content.

**Comment by dummdidumm** [comment]
Version 3 of this plugin will leave tags as-is, so writing `<div></div>` won't be reformatted to `<div />` anymore. We keep formatting `<input>` as `<input />` to align with Prettier.

**Comment by danielniccoli** [comment]
I'm not in favour of aligning with Prettier in case of void elements. They're explicitly mentioned as not self-closing. Prettier takes an opinionated stance on the matter and imposes its choice on the developer. I wouldn't argue, if it were up to the developer, but the HTML specs are very clear on void elements.

For now, I can enable `svelteStrictMode`, but as I understand it's deprecated.

**Comment by danielniccoli** [comment]
Related https://github.com/sveltejs/svelte/issues/11052

**Comment by mustafa0x** [comment]
Related: https://github.com/awmottaz/prettier-plugin-void-html

Doesn't work with .svelte files thought.

**Comment by shadow-identity** [comment]
Rich [mentioned](https://github.com/sveltejs/svelte/issues/11052#issuecomment-2063845896) that the latest version on _prettier-plugin-svelte_ should prevent prettier from braking html by converting html tags into void tags. But as I can see, 3.2.3 still replaces `<br>` with `<br />`. Is it planned to fix it?

**Comment by dummdidumm** [comment]
No this will stay as is for the foreseeable future to align with Prettier's HTML formatting.
