### ISSUE TITLE
Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag in v3

### ISSUE THREAD

**Issue by marekdedic** [sveltejs/prettier-plugin-svelte#388]
Hi,
after updating to v3, prettier complains about adjacent tags in Svelte code - AFAIK you can do that in Svelte, but prettier thinks it's dealing with JSX...

See here: https://github.com/skaut/shared-drive-mover/pull/1352

**Comment by dummdidumm** [comment]
Please provide more details.
- how do you invoke Prettier? CLI? Through an extension? If the latter, through which one?
- Do you have a `.prettierrc`? Prettier v3 does not do any autodiscovery of plugins anymore, so you need one. Also see [the migration guide](https://github.com/sveltejs/prettier-plugin-svelte#how-to-migrate-from-version-2-to-3)

**Comment by marekdedic** [comment]
Yep, adding a proper `.prettierrc` fixed this. Thanks!
