### ISSUE TITLE
svelteAllowShorthand doesn't work in Version 3

### ISSUE THREAD

**Issue by dispbd** [sveltejs/prettier-plugin-svelte#396]
I read about the migration, and about the breaking change in the behavior of svelteAllowShorthand. But I still don't understand if it's possible to make it work like before (as in version 2) if svelteAllowShorthand = true?
![](https://i.vgy.me/Jq0p70.png)
That is, now this setting does not work for me. And it turns out that if this is how it should be, then the setting is useless.
Or is it a bug?
Or am I misunderstanding the meaning of this setting in version 3?

**Comment by dummdidumm** [comment]
Please post a code snippet and how it formats things given your settings, and how you expect it to be formatted

**Comment by dispbd** [comment]
**Now formatted like this:**
![](https://i.vgy.me/Q9IMTn.png)
**It is expected to be like this:**
![](https://i.vgy.me/Ip52Dc.png)

**Comment by dummdidumm** [comment]
This works as expected. Whether or not empty elements/components should self-close is now left to the user - in other words, if you write `<div />` or `<Component />` that stays as is, and so does `<div></div>/<Component></Component>`. If svelteStrictMode is turned on, it will still only allow `<div></div>` notation for elements (but it will leave your components alone)

**Comment by dispbd** [comment]
That is, I understand correctly that the svelteAllowShorthand setting is now meaningless?
How to make the behavior like in the second version?

It turns out that you changed the behavior, because it did not suit many. But what about those who are satisfied with this behavior?
That is, you have deprived the user of choice and the ability to decide for himself what is more convenient for him.
Why not make a switch? That is, by default, let it work as it is (as in version 3), but if the user changes the setting value, then the behavior will work as in version 2.

**Comment by dummdidumm** [comment]
The shorthand option was never about self closing tags, it's only about attribute/bindings shorthands: https://github.com/sveltejs/prettier-plugin-svelte#svelte-allow-shorthand

You're not deprived of your choice, either. You can turn this into `<div />` yourself and it will _not_ format it back into `<div></div>`

**Comment by theetrain** [comment]
Given the following .prettierrc:

```json
{
  "plugins": ["prettier-plugin-svelte"],
  "overrides": [
    {
      "files": "*.svelte",
      "options": {
        "parser": "svelte",
        "svelteStrictMode": true,
        "svelteAllowShorthand": false
      }
    }
  ]
}
```

This code:

```html
<div role="{role}">Test</div>
```

Gets formatted as:

```html
<div {role}>Test</div>
```

Expected behaviour is to remain unchanged.

Using:

prettier@3.1.1
prettier-plugin-svelte@3.1.2

**Comment by dispbd** [comment]
@theetrain We were not talking about self-closing properties, but about self-closing tags.
That is, so that this code:
`<div></div>`
Formatted like this:
`<div />`

It's sad that the concept of the Prettier developers is to kill all the variety of possibilities. A very "long-range" approach :unamused:
Since this makes writing to them pointless, I am closing the issue. Thanks to all!
