### ISSUE TITLE
Prettier does not format .svelte files when run with "prettier --write ."

### ISSUE THREAD

**Issue by peterpeterparker** [sveltejs/prettier-plugin-svelte#407]
Hi,

I'm not sure if this is an issue or a limitation when using the plugin with Prettier v3, but I've noticed that it doesn't format Svelte files in my project anymore.

I'm using Prettier v3 along with the latest version of this plugin. It fails to format Svelte files when the path in the command line is set to `.`.

Running `prettier --write .` doesn't process Svelte files. However, enforcing it using `prettier --write './**/*.{ts,js,mjs,json,scss,svelte,html}'` seems to work.

My `.prettierrc` is the following:

```
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
	"plugins": ["prettier-plugin-svelte", "prettier-plugin-organize-imports"],
	"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

Note that with or without the `overrides`.

**Comment by dummdidumm** [comment]
See [the last part of the migration section](https://github.com/sveltejs/prettier-plugin-svelte#how-to-migrate-from-version-2-to-3) - this is currently a bug in prettier, a release for the fix is still pending on their side

**Comment by peterpeterparker** [comment]
Gotcha! Thanks for the feedback
