### ISSUE TITLE
npm package updated to 3.1.0 but the changes haven't been pushed to this repo

### ISSUE THREAD

**Issue by polyzen** [sveltejs/prettier-plugin-svelte#408]

**Comment by KieranP** [comment]
NPM account compromised possibly? Same thing happened for svelte-preprocess

**Comment by ollema** [comment]
I don't think the account is compromised, the more likely explanation is that svelte 5 related changes were hidden:
https://diff.intrinsic.com/prettier-plugin-svelte/3.0.3/3.1.0

e.g. snippet/render changes

**Comment by dummdidumm** [comment]
I just forgot to push the changes, they're up now 👍
