### ISSUE TITLE
Prettier plugin svelte does not format typescript code inside `@const` tag

### ISSUE THREAD

**Issue by lts20050703** [sveltejs/prettier-plugin-svelte#442]
It looks like Prettier does not format typescript code inside `@const` tag

For example, prettier will successfully format the code below
```svelte
{@const x = a[0]}
```

But it does not format the code below
```svelte
{@const x = a[0] as number}
```

Workaround: None found yet.

**Comment by dummdidumm** [comment]
Closing as duplicate of #447
