### ISSUE TITLE
⚠️ unmet peer prettier@"^1.16.4 || ^2.0.0": found 3.3.1

### ISSUE THREAD

**Issue by Valexr** [sveltejs/prettier-plugin-svelte#444]
<img width="614" alt="Screenshot 2024-06-06 at 07 17 56" src="https://github.com/sveltejs/prettier-plugin-svelte/assets/5656366/3c3e7c07-0b71-4202-a969-8efeea98a6c0">

**Comment by dummdidumm** [comment]
Update prettier-plugin-svelte to the latest version
