### ISSUE TITLE
.prettierignore ignored

### ISSUE THREAD

**Issue by orefalo** [sveltejs/prettier-plugin-svelte#445]
with this plugin activated,
the setting from .prettierignore are.. well .. ignored.

Which is not expected

**Comment by dummdidumm** [comment]
Please provide more steps to reproduce this:
- what extension do you use for formatting?
- where in the project does the `.prettierignore` exist? Is it at the top level or nested somewhere?

There's a known issue in Prettier that it does not take into account nested `.prettierignore`s, which is an upstream issue.

**Comment by orefalo** [comment]
Sure,
very simple, the project is public.
the plugin is disabled as of now, so you will need to add `	"plugins": ["prettier-plugin-svelte"]` to `.prettierrc` 
I am trying to get prettier to ignore the files in "/unchecked", this exclusing is defined in `.prettierignore`

1. git clone git@github.com:orefalo/svelte-treeviews.git
2. `npm i` or `pnpm i`
3.  then try npm format or prettier directly

when the plugin is turned-on you will see this

![CleanShot 2024-06-12 at 12 32 50](https://github.com/sveltejs/prettier-plugin-svelte/assets/52085/5db6d3c4-5326-430e-803f-65c483b50d05)

which clearly shows that the `.prettierignore` is.. well ignored ;-)

**Comment by orefalo** [comment]
nevermind, it's a filename typo
