### ISSUE TITLE
svelteStrictMode: true adds quotes around attributes for Svelte 5

### ISSUE THREAD

**Issue by Tagman** [sveltejs/prettier-plugin-svelte#454]
Hi,

If I understood the documentation right. `svelteStrictMode: true` should format attributes like this `<Checkbox bind:checkState={toolbox.expertMode}></Checkbox>`.

But running `npx prettier --write .` adds the quotes back to the attribute.

When I disable the strict mode, the quotes get removed. Is the documentation wrong? 

<details>
<summary>.prettierrc</summary>

```
{
    "trailingComma": "es5",
    "tabWidth": 4,
    "arrowParens": "always",
    "bracketSpacing": true,
    "endOfLine": "lf",
    "printWidth": 120,
    "singleQuote": false,
    "svelteSortOrder": "options-scripts-markup-styles",
    "svelteStrictMode": false,
    "bracketSameLine": true,
    "svelteAllowShorthand": true,
    "semi": true,

    "plugins": ["prettier-plugin-svelte"],
    "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

</details>

**Comment by dummdidumm** [comment]
I'm not able to reproduce this. Are you sure you're on the lastest version? If so, please provide a reproduction repository

**Comment by Tagman** [comment]
Weirdly enough, I also cannot reproduce it anymore. I updated to  "svelte": "^5.0.0-next.225".
This was the only change.

Thanks for the response, though. I guess this can be closed now. :)
