### ISSUE TITLE
How to fallback to default prettier formating in non svelte files

### ISSUE THREAD

**Issue by SteveALee** [sveltejs/prettier-plugin-svelte#465]
In my svelte git hub project (edited with vs code) I also have a plain HTML + JS + CSS group of files (in static) but prettier will not work on them unless I disable the svlete plugin.

svelte plugin is enabled in my .prettier.rc with 

```
{
  "plugins": ["prettier-plugin-svelte"],
  "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }],
....
}
```
I have to invalidate the first line when editing my vanilla files and then restore it when editing the svelte files.

I can find no options in the plugin or prettier docs for how to restrict plugin processing to certain folders, I'm also surprised the plugin is not restricted to .svelte files

**Comment by dummdidumm** [comment]
This should work as you expected. Please provide a reproduction so we can properly look into this

**Comment by SteveALee** [comment]
Thanks for confirmining. I'll work on a minimal repro next week.

**Comment by SteveALee** [comment]
Here's a minimal setup - see REAME - https://github.com/SteveALee/prettier-plugin-svelte-bug/tree/master
