### ISSUE TITLE
svelteSortOrder: 'none' deletes <style> tags unless followed by HTML comment.

### ISSUE THREAD

**Issue by andreasputlitz** [sveltejs/prettier-plugin-svelte#472]
I first realized this issue through this phenomenon:

If you add a #region tag after the markup, but don't add an #endregion tag after that, and you have a <style> tag at the end of the page, everything after the last HTML tag will be erased, including the style tag and any comment after the last HTML tag.

I was adding #region markers to my page-files, and all of my style-tags have disappeared from the pages.

This is fine:

```
<!-- #region MARKUP -->
<body></body>
<!-- #endregion -->

<!-- #region STYLES -->
<style></style>
<!-- #endregion -->
```

But this:

```
<!-- #region MARKUP -->
<body></body>
<!-- #endregion -->

<!-- #region STYLES -->
<style></style>
```

Will be formatted to this:

```
<!-- #region MARKUP -->
<body></body>
```

Effectively erasing the styles. Happened to me on all of my pages.

**Comment by dummdidumm** [comment]
Please provide a code example. If you use triple back tick (` repeated three times) you can paste whatever you want in there and it's preserved:

```
<!-- hello -->
# region
bla
```

**Comment by andreasputlitz** [comment]
Btw, different issue, but the reason why I set `svelteSortOrder: 'none'` in the first place, is because if you have a sort order defined (or at least with the default one), it doesn't allow for HTML comments after the script tags, which was conflicting with my use of #region-#endregion tags. 

My use case is: in long components, I would like to wrap my logic, markup, and style in those region-tags, so I can fold them away. But the very last #endregion tag (which has to be inside of a comment) would always be moved before the style-tags by svelte-prettier. Probably because it thinks that the comment is part of the markup, which is supposed to go before the style-tags. If you could change that behaviour, to ignore comments in the sort-order, I would gladly refrain from setting `svelteSortOrder: 'none'`.

**Comment by andreasputlitz** [comment]
Thanks 👍🏼

**Comment by andreasputlitz** [comment]
Just FYI, I am currently on version 5.2.10 and the issue still persists. Not sure if it should already be resolved in the current version.
