### ISSUE TITLE
SCSS parsing

### ISSUE THREAD

**Issue by jgelens** [sveltejs/prettier-plugin-svelte#51]
What's the best way to let Prettier parse the <style> tags as SCSS?

**Comment by UnwrittenFun** [comment]
to my knowledge it should be already, are you seeing something different?

**Comment by makmm** [comment]
it won't work with stylus either

**Comment by dummdidumm** [comment]
Scss is supported, sass and stylus are not. The latter two will not be formatted anymore in the latest release. Note that you need to set `lang="sass"` / `lang="stylus"`.
