### ISSUE TITLE
prettier-ignore is ignored

### ISSUE THREAD

**Issue by taylorzane** [sveltejs/prettier-plugin-svelte#59]
The following snippet of code will get formatted regardless of whether the `<!-- prettier-ignore -->` comment is above the line. The standard prettier html parser handles this case.

```html
<script>
// whatever
</script>

<!-- prettier-ignore -->
<span>[</span><span>{value}</span><span>]</span>

<style>
/* whatever */
</style>
```

The spans need to stay on one line as this component is inside of a `<pre>` tag and being on new lines modifies the outcome. (That's a separate issue that can't necessarily be handled by #28, so the `prettier-ignores` should be respected.)

**Comment by foodwaterwifi** [comment]
This would be greatly appreciated.....................

**Comment by Conduitry** [comment]
Implemented in 1.1.0.

**Comment by MarcCoet** [comment]
It is not working for me. I updated dependencies to
```
    "prettier": "^2.0.5",
    "prettier-plugin-svelte": "^1.1.0",
```
and this
```
    <!-- prettier-ignore -->
    <p>A veryyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy long sentence to make the tag wrap</p>
```
still wraps.

The prettier plugin seems to kick in since my `<script>` and `<style>` tags get reordered properly.

Is anyone else having issues with this?

**Comment by jonas-veselka** [comment]
Also not working for me. I need this line to be ignored because of unwanted spaces from the new lines.
```
<!-- prettier-ignore -->
{@html text1}<a href='#'>{@html linkText}</a>{@html text2}
```

**Comment by b1m1nd** [comment]
So after finally getting SCSS working with svelte beta/vsCode (and wanting to use .pug, which I know is not supported atm). I looked for away to omit <template> tag from being formatted. I found this thread and tried the above and it seems to be working for me?
![image](https://user-images.githubusercontent.com/55322556/82975632-49ca5c00-9f9a-11ea-814a-c382d792bad2.png)
One thing I know that I did is make a .prettierrc in my root app folder with 
```json
// .prettierrc
{
  "svelteSortOrder": "scripts-markup-styles",
  "svelteStrictMode": true,
  "svelteBracketNewLine": true,
  "svelteAllowShorthand": false
}
``` Not sure that matters any though. As it seems to work in .css/.html/.svelte files shown in screencap. Any thing I can do to help just ask I will spend time(though I am quite the noob).

**Comment by jonas-veselka** [comment]
> ```json
> // .prettierrc
> {
>   "svelteSortOrder": "scripts-markup-styles",
>   "svelteStrictMode": true,
>   "svelteBracketNewLine": true,
>   "svelteAllowShorthand": false
> }
> ```
This unfortunately doesn't work for me.

**Comment by will-stone** [comment]
I just had this issue when trying to inject a dynamic style tag and found this worked, no prettier-ignore required:

```svelte
{@html `<${'style'} class="block">
...
</style>`}
```

My other issue was that postCSS was clobbering the style tag: hiding it in the nested string got around that. Without doing that results in Prettier doing this:

```svelte
{@html `<style class="block ✂prettier:content✂="LmFuaW1hdGlvbk5hbWUgewogI..."></style>`}
```

**Comment by luizschiestl** [comment]
Any progress or workaraound on that? Note that svelte files listed in `.prettierignore` are also not ignored, so my only current option is to set `"svelte.plugin.svelte.format.enable": false` in VS Code settings which will unfortunately disable formatting for all svelte files.

**Comment by nauta** [comment]
In VS Code, using the "Svelte Beta" extension instead of the more popular "Svelte" extension from James Birtles (that uses this plugin's older 0.7.0 version), fixed at least the prettier-ignore feature in html for me.

**Comment by luizschiestl** [comment]
> In VS Code, using the "Svelte Beta" extension instead of the more popular "Svelte" extension from James Birtles (that uses this plugin's older 0.7.0 version), fixed at least the prettier-ignore feature in html for me.

Didn't work for me. Do you mind sharing your VS Code settings?

**Comment by b1m1nd** [comment]
Really stabbing in the dark here... Cause I did some real wacky things in my process.

Uninstall prettier and all svelte extension. > Installed prettier > installed old svelte > load svelte a file > uninstall old svelte extension > install **Svelte Beta** > reload vsCode.

Not sure if this will work but it is how I had installed things.

**Comment by dummdidumm** [comment]
This issue is now about multiple things at once. The original issue, supporting `prettier-ignore`, is implemented, so I'm going to close. If it does not work for you when using the VSCode extension, I suggest to take a second look at the [setup instructions](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#setup) to make sure you don't have an old extension installed and don't treat Svelte as HTML.

The issues listed in the following have other, different reasons:

> I just had this issue when trying to inject a dynamic style tag and found this worked, no prettier-ignore required:
> 
> ```svelte
> {@html `<${'style'} class="block">
> ...
> </style>`}
> ```
> 
> My other issue was that postCSS was clobbering the style tag: hiding it in the nested string got around that. Without doing that results in Prettier doing this:
> 
> ```svelte
> {@html `<style class="block ✂prettier:content✂="LmFuaW1hdGlvbk5hbWUgewogI..."></style>`}
> ```

This is another symptom of #70 

> Also not working for me. I need this line to be ignored because of unwanted spaces from the new lines.
> 
> ```
> 
> {@html text1}<a href='#'>{@html linkText}</a>{@html text2}
> ```

`prettier-ignore` does not work this way. It only ignores the next _node_, not the next _line_. So it will only keep the first `{@html...` node unformatted. To achieve what you desire, but the `prettier-ignore` comment above the node that contains the code. Example:

```
<!-- prettier-ignore -->
<div>
     {@html text1}<a href='#'>{@html linkText}</a>{@html text2}
</div>
```

> Note that svelte files listed in `.prettierignore` are also not ignored.

I created #131 for that

**Comment by DhyeyMoliya** [comment]
`<!-- prettier-ignore -->` does not work in `.svelte` files for `<script src="...">` and `<style src="...">`.

**Comment by dummdidumm** [comment]
#130  will fix this

**Comment by Mlocik97** [comment]
I have this problem again.

**Comment by codingwithchris** [comment]
`<!-- prettier-ignore -->` still does not work in:
```
"prettier": "^2.6.2",
"prettier-plugin-svelte": "^2.7.0",
```
@dummdidumm Your example here does not work:
```
<!-- prettier-ignore -->
<div>
     {@html text1}<a href='#'>{@html linkText}</a>{@html text2}
</div>
```

prettier still formats everything in this node... nothing I can do will prevent prettier from running in a svelte file on any line. I was attempting to do this to bypass #240 which still seems to be a bug.

**Comment by dummdidumm** [comment]
Please open a new issue with a detailed reproduction (can't reproduce this given your code snippet) instead of posting in 3 closed ones.
