### ISSUE TITLE
Very slow when used with prettier-atom

### ISSUE THREAD

**Issue by severo** [sveltejs/prettier-plugin-svelte#60]
After installing prettier-plugin-svelte, saving a .svelte file in Atom (with [prettier-atom](https://atom.io/packages/prettier-atom) formatting on save) turns to be very slow.

I published explanations to replicate here: https://github.com/severo/atom_prettier_svelte

Note that calling prettier from the CLI is instantaneous.

**Comment by Fil** [comment]
I can confirm the issue on @severo's project — takes 15s to save the Large.svelte file. (Atom 1.40.1, prettier-atom 0.57.3,  macOS 10.14.6).

**Comment by chrisbrown-io** [comment]
I've been having the same issue when using `prettier-plugin-svelte` with [SublimeJsPrettier](https://github.com/jonlabelle/SublimeJsPrettier). 

Narrowed it down to being an issue with the `cursorOffset`/`--cursor-offset` argument being passed to the prettier cli.

It doesn't currently look like there is a way to disable this within `prettier-atom` [(looks like they're working on it)](https://github.com/prettier/prettier-atom/blob/74620f0b87a10b7359b1a6ef647157adb72a5d92/src/executePrettier/executePrettierOnBufferRange.js#L73), but this is definitely the cause of the issue.

I'm not sure if this is an issue with the plugin internally calculating the cursor-offset, or prettier itself - will look into if I get more time.

e.g

When taking a moderately large `.svelte` file (100 lines+), without `--cursor-offset` argument, processed in < 1s:

```
prettier Example.svelte --config .prettierrc --loglevel debug
```

Whereas if you add the `--cursor-offset` argument, it's taking anywhere from 10s upwards:

```
prettier Example.svelte --config .prettierrc --loglevel debug --cursor-offset 0
```

**Comment by UnwrittenFun** [comment]
Very strange, thanks for the investigation @chrisbrown-io

**Comment by antonbrams** [comment]
do we have any solution for this issue? For some reason the prettier-plugin-svelte in combination with prettier-atom works freaking slow. With plain .js prettier-atom performs good. How can i fix a minute freeze of a svelte file?

**Comment by ThibGonceDKT** [comment]
Still have this issue, do we have any solution for this ?
