### ISSUE TITLE
Always put <svelte:options> at top of file

### ISSUE THREAD

**Issue by Tyilo** [sveltejs/prettier-plugin-svelte#73]
I think it would be prettier if the `<svelte:options>` tag was always at the top of file, before scripts and styles.

Maybe `<svelte:head>` should also be at the top (but not any of the other `<svelte:...>` tags)?

**Comment by rixo** [comment]
Currently source maps are off when `<script≥` is not at the very top... Maybe wait for this to be fixed before? https://github.com/sveltejs/svelte/issues/3906

**Comment by dummdidumm** [comment]
I'm against `<svelte:head>` but I think `<svelte:options>` makes sense.

**Comment by aabounegm** [comment]
> Maybe wait for this to be fixed before? [sveltejs/svelte#3906](https://github.com/sveltejs/svelte/issues/3906)

The referenced issue has been fixed. Any updates on this one?

**Comment by dummdidumm** [comment]
From #165 : We could also make this configurable by enhancing the sort order.
