### ISSUE TITLE
svelteAllowShorthand not available on the npm registry

### ISSUE THREAD

**Issue by acewf** [sveltejs/prettier-plugin-svelte#75]
Hi guys!

Although the readme file makes reference to **svelteAllowShorthand** option,
this option isn't available on the current version published on npm 
https://www.npmjs.com/package/prettier-plugin-svelte
which is version **0.7.0** what matches the version on package on the repo

https://github.com/UnwrittenFun/prettier-plugin-svelte/blob/0debb22edc1a1eb49c5925f9f5a133d35ffdf0b7/package.json

The **svelteAllowShorthand** is already merged into master
https://github.com/UnwrittenFun/prettier-plugin-svelte/blob/0debb22edc1a1eb49c5925f9f5a133d35ffdf0b7/src/options.ts
So we should get a new version..
Can you check what is going on with your CI, maybe there is something wrong stopping to trigger a new version when merging code to master!?

Thanks

**Comment by Conduitry** [comment]
This has been released in 1.0.0.
