### ISSUE TITLE
Error when including values in props

### ISSUE THREAD

**Issue by fkereki** [sveltejs/prettier-plugin-svelte#80]
If I include  ` || '' `  in the props, I get an error; without that, the file is formatted correctly.

**Input:**

```
<div class="account" >
  <div class="accounttitle" >
    <p >Account</p>
      <DynamicTooltip content={$t(message) || ''} >
        <Icon icon={{ name: 'info_outline' }}  / >
      </DynamicTooltip >
  </div >
</div >
 
<script>
  /* JavaScript goes here... */
</script>
```

**Output:**

SyntaxError: Unexpected closing tag "DynamicTooltip". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (6:7)
```
  4 |       <DynamicTooltip content={$t(message) || ''}>
  5 |         <Icon icon={{ name: 'info_outline' }} />
> 6 |       </DynamicTooltip>
    |       ^
  7 |   </div>
  8 | </div>
  9 |  
```

**Comment by Conduitry** [comment]
`<Icon icon={{ name: 'info_outline' }}  / >` isn't valid Svelte syntax. If the extra space between the `/` and the `>` is removed, I'm not seeing any incorrect behavior in the latest version.
