### ISSUE TITLE
Want to transfer this to the sveltejs org and make it an official plugin?

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/prettier-plugin-svelte#86]
Hi there! Would you be interested in the Svelte maintainers adopting this and it becoming an official plugin?

I'm using Svelte and Prettier at work, and I've recently gotten the okay to spend work hours on this, so for the immediate future it would probably be me doing the renovating and refreshing. I've also spoken with other Svelte maintainers and they agree that this is something it would be good to have an official solution for.

Let me know! Thanks!

**Comment by mdorda** [comment]
@UnwrittenFun It would be amazing if this awesome plugin stayed alive!

**Comment by yagebu** [comment]
@Conduitry: how about a temporary fork at the svelte org until @UnwrittenFun replies?

**Comment by UnwrittenFun** [comment]
@Conduitry hey, sorry just saw this. I'm happy for this to happen, let me know what you need me to do

**Comment by ryanatkn** [comment]
@UnwrittenFun Thank you so much for all of the work you put into Svelte tools. You made my experience adopting Svelte immeasurably more pleasant than it would have been otherwise, between this, svelte-vscode, and svelte-language-server.

In open source it can be difficult to convey appreciation, and sometimes authors and users miss out on sharing the great stuff that's happening. I think many people including me are sincerely grateful for everything you've done on these projects. Thank you!! 👍 💯 👏

**Comment by Conduitry** [comment]
@UnwrittenFun Hi, great! First step would be to transfer this over to the sveltejs org, which I believe you should be able to do at https://github.com/UnwrittenFun/prettier-plugin-svelte/settings - And then there's the question of what to do with the npm package ownership. You could add me as a member of the existing project (same username there as here), or we could switch to a scoped package name like `@sveltejs/prettier-plugin` as part of the transfer. I'd probably slightly prefer going to a scoped name (as it makes it more clear that this would be an 'official' plugin now, controlled by the `sveltejs` npm org), and would make it easier to share publishing privileges across the core Svelte maintainers. The main trouble here would be people getting stuck on `prettier-plugin-svelte` and not realizing future work was happening under a different package name. Hopefully deprecating the package in npm once there's a replacement `@sveltejs/prettier-plugin` would mostly take care of that.

**Comment by UnwrittenFun** [comment]
@Conduitry Github doesn't want to let me transfer to the sveltejs org 
![image](https://user-images.githubusercontent.com/3743418/80812320-9f8c2e00-8bbf-11ea-8411-93b25d4799fb.png)

**Comment by Conduitry** [comment]
Huh I didn't realize that's how it worked. I've invited you to become a member of the org so we can at least get it transferred, and then we can figure out how we want this organized from there.

**Comment by UnwrittenFun** [comment]
Transferred 🙂

**Comment by Conduitry** [comment]
Thank you! For now I've switched you over to an outside collaborator - so you can still push to this repo. Could you add me as a maintainer on the npm package? https://www.npmjs.com/~conduitry (Apologies if you've already done this and I just can't see it in their UI for whatever reason!)
