### ISSUE TITLE
Empty style and script tags are expanded into three lines

### ISSUE THREAD

**Issue by clitetailor** [sveltejs/prettier-plugin-svelte#87]
I'm using Svelte with svelte-preprocessor. The following lines:

```html
<script src="./index.ts"></script>

<style src="./index.css"></style>
```

is formatted as:

```html
<script src="./index.ts">

</script>

<style src="./index.css">

</style>
```

My expected output should be the same as first one. Is this some kind of bug?

Thanks!

**Comment by ehrencrona** [comment]
With the current code the empty line will be gone and it turns it into:

```
<script src="./index.ts">
</script>
```
