### ISSUE TITLE
Prevent unnecessary quotes around expressions 

### ISSUE THREAD

**Issue by QuantumInformation** [sveltejs/prettier-plugin-svelte#92]
I want to prevent putting commas around these svelte vars

            `<input required placeholder="Username" bind:value="{username}" />`

ie I want to keep

            <input required placeholder="Username" bind:value={username} />

**Comment by Conduitry** [comment]
I assume by "commas" you mean "quotes". This is already happening as far as I can tell. Using 1.1.0, when I format `<input required placeholder="Username" bind:value={username} />` this is left unchanged, and when I format `<input required placeholder="Username" bind:value="{username}" />` the quotes are removed.
