### ISSUE TITLE
Resolve svelte/prettier relative to user's workspace

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/prettier-plugin-svelte#93]
Currently  the `prettier` / `svelte` packages are resolved relative to where the plugin module lives - but that may be the node_modules folder of e.g. the Svelte Beta Plugin, not the user's workspace. You can check that by using require.resolve and look at what the path is. To use `prettier` / `svelte` relative to the user's workspace, logic similar [to this](https://github.com/sveltejs/language-tools/blob/master/packages/language-server/src/plugins/importPackage.ts) is needed.

**Comment by Conduitry** [comment]
Do you know whether Prettier even has a concept of 'the current workspace'? I don't see anything in [the plugin API docs](https://prettier.io/docs/en/plugins.html) that indicate that plugins know the path of the file being formatted.

**Comment by dummdidumm** [comment]
I don't see any, either, but we could use the `options` object and add a custom parameter. You could then check "is this set?" and if yes, do a require relative to that path, else do require normally.

**Comment by dummdidumm** [comment]
This works as expected, I just was doing something wrong.
