### ISSUE TITLE
Quotes inside if blocks

### ISSUE THREAD

**Issue by emagnus** [sveltejs/prettier-plugin-svelte#94]
Inside if blocks, double quotes are replaced by single quotes when running prettier with this plugin. For example,

    {#if foo === "bar"}
      <div>baz</div>
    {/if}

is changed to

    {#if foo === 'bar'}
      <div>baz</div>
    {/if}

Most (all?) other places double quotes are enforced. Is this intentional, or can quotes inside if blocks also be enforced as double?

**Comment by eldridge** [comment]
[The plugin appears to be explicitly setting prettier options in the implementation.](https://github.com/sveltejs/prettier-plugin-svelte/blame/master/src/embed.ts#L22).  If I remove that option, the plugin respects the local .prettierrc.yml file.  [I've created a PR here.](https://github.com/sveltejs/prettier-plugin-svelte/pull/101)

**Comment by brgrz** [comment]
How does this plugin behave when Prettier extension is not installed?

I'm seeing the opposite, changing single quotes to double as described here
https://github.com/sveltejs/language-tools/issues/23

**Comment by dummdidumm** [comment]
This plugin is packages with the extension. So if you want to configure it use a `.prettierrc` config file. The linked issue contains a comment now about the setting you want.
