### ISSUE TITLE
which vscode svelte extension to use

### ISSUE THREAD

**Issue by jthegedus** [sveltejs/prettier-plugin-svelte#97]
Two different places in the svelte docs point to two different svelte extensions:

- svelte beta - by svelte
- svelte - by james birtles

which should people be using to get the effects of this plugin?

**Comment by Conduitry** [comment]
You don't have to use either. This is a plugin for Prettier, and not inherently related to VS Code.

Svelte Beta is under active development, and is based on Svelte by James Birtles, which is not under active development. If there are some things in the Svelte docs that you feel should be clarified, please open an issue there.

**Comment by jthegedus** [comment]
Yes, I recognise this is just a plugin for prettier. However, the line

>This plugin comes with Svelte for VS Code and Svelte for Atom so just install extension for your favorite editor and enjoy.

was not that easy for me. I needed to disable the older (more popular by VSCode installs) VSCode extension and install the "svelte beta" extension to get this behaviour. This quote links to the old one. I am unsure if this is just me, or common to everyone.

Following the instructions to install this and prettier on the CLI also didn't work as I expected. The Prettier VSCode ext threw an error when forced to run on `.svelte` files and didn't seem to respect that this plugin was installed.

Taking the Sapper template and setting up this plugin took me half an hour of debugging before I was linked to the beta VSCode plugin which works as advertised here.
