### ISSUE TITLE
Code is formatted wrongly, breaking strings

### ISSUE THREAD

**Issue by fkereki** [sveltejs/prettier-plugin-svelte#98]
When I format the following code:

    <div class="details-header">
      <div class="details-title">{$t('details.title')}</div>
      <div class="more-info" on:click="toggleTooltips()">
         {#if showTooltips}
            <Icon
               icon={{
                  name: 'close',
                className: 'text-size-normal material-icons align-middle text-color-red'
             }}
          />
        {:else}
          <Icon
          icon={{
            name: 'help_outline',
            className: "text-size-normal material-icons align-middle text-color-red"
          }}
        />
        {/if}
      </div>
    </div>

the result is broken -- notice the split string in the 4th line, the one starting with `text-size-normal material-icons` -- part of the text goes into the next line, causing a JavaScript error.

    <div class="details-header">
       <div class="details-title">{$t('details.title')}</div>
         <div class="more-info" on:click="toggleTooltips()">
            {#if showTooltips} <Icon icon={{ name: 'close', className: 'text-size-normal material-icons
            align-middle text-color-red' }} /> {:else} <Icon icon={{ name: 'help_outline', className:
            "text-size-normal material-icons align-middle text-color-red" }} /> {/if}
       </div>
     </div>

I'm using the latest version of Prettier (github:prettier/prettier) plus the 1.1.0 version of prettier-plugin-svelte

**Comment by BjornLuG** [comment]
I've tried the code and mine gave an error instead. Turns out on the third line, the `on:click="toggleTooltips()"` part should be wrapped with curly braces instead of quotes. After changing to `on:click={toggleTooltips()}` it worked again.

**Comment by fkereki** [comment]
@BjornLuG  And what happens with the string problem I showed? Does it keep happening?

**Comment by BjornLuG** [comment]
Nope. Mine prints properly (except that the icon attribute of Icon is all in one line).

Here's my output:
```svelte
<div class="details-header">
  <div class="details-title">{$t('details.title')}</div>
  <div class="more-info" on:click={toggleTooltips()}>
    {#if showTooltips}
      <Icon
        icon={{ name: 'close', className: 'text-size-normal material-icons align-middle text-color-red' }}
      />
    {:else}
      <Icon
        icon={{ name: 'help_outline', className: 'text-size-normal material-icons align-middle text-color-red' }}
      />
    {/if}
  </div>
</div>
```

I'm using prettier@2.0.5, prettier-plugin-svelte@1.1.0. And my prettier config:

```json
{
  "proseWrap": "never",
  "semi": false,
  "singleQuote": true,
  "trailingComma": "none",
  "svelteBracketNewLine": true
}
```

**Comment by nickarora** [comment]
We are definitely experiencing this:

Before formatting:

```
<img src={url} alt={title} />
```

after
```
<img src="{url}" alt="{title}" />
```

prettier config:
```
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "proseWrap": "never",
  "semi": false,
  "singleQuote": true,
  "svelteSortOrder" : "scripts-markup-styles",
  "svelteStrictMode": true,
  "svelteBracketNewLine": true
}
```
