### ISSUE TITLE
"Unexpected closing tag" error

### ISSUE THREAD

**Issue by fkereki** [sveltejs/prettier-plugin-svelte#99]
When formatting the following code

    <div class="account" >
      <div class="accounttitle" >
        <p >Account</p>
            <DynamicTooltip content={$t(message) || ''} >
            <Icon icon={{ name: 'info_outline' }}  />
              </DynamicTooltip >
      </div >
    </div >
     
    <script>
      /* JavaScript goes here... */
    </script>

I get an error:

      9 |  
    SyntaxError: Unexpected closing tag "DynamicTooltip". It may happen when the tag has already 
    been closed by another tag. For more info see 
    https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (6:7)
      4 |         <DynamicTooltip content={$t(message) || ''} >
      5 |         <Icon icon={{ name: 'info_outline' }}  />
    > 6 |       </DynamicTooltip >
        |       ^
      7 |   </div >
      8 | </div >

If  don't use `||` in the 4th line of the original code, the error doesn't appear.

I'm using the latest version of Prettier from GitHub, and version 1.1.0 of prettier-plugin-svelte

**Comment by sassman** [comment]
Having the same issue with way simpler markup already:

```html
<p>
  <p>
    foo
  </p>
</p>
```

**Comment by mikenikles** [comment]
@sassman you can't nest `<p>` elements.

**Comment by sassman** [comment]
@mikenikles I never thought much about it, but sure, it does not make sense to nest them but that it is actually by spec forbidden, I had no idea.

> The P element represents a paragraph. It cannot contain block-level elements (including P itself).

Thanks for highlighting that

**Comment by fkereki** [comment]
It seems that if you wrap the `{{...}}` in quotes, the error doesn't show.

**Comment by dummdidumm** [comment]
No longer reproducible with the latest version of Svelte, Prettier and prettier-plugin-svelte.
